# Generated by Django 4.1.3 on 2022-11-06 16:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='source_doc',
            field=models.FileField(default=None, upload_to='uploads/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='physician',
            name='hospital',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='records.hospital'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='physician',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.condition'),
        ),
        migrations.AlterField(
            model_name='document',
            name='physician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.physician'),
        ),
        migrations.AlterField(
            model_name='document',
            name='prescribed_drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.drug'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='website',
            field=models.URLField(default=None),
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('dosing_regimen', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('prescribed_drug', models.ManyToManyField(to='records.drug')),
            ],
        ),
        migrations.AlterField(
            model_name='physician',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.specialty'),
        ),
    ]
