# Generated by Django 4.1.3 on 2022-11-06 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_specialty_document_source_doc_physician_hospital_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialty',
            options={'verbose_name_plural': 'Specialties'},
        ),
    ]
