# Generated by Django 4.1.3 on 2022-11-07 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_alter_specialty_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='prescribed_drug',
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_attended', models.DateField()),
                ('comment', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.document')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.hospital')),
                ('physician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.physician')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.treatment')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='prescribed_drug',
            field=models.ManyToManyField(to='records.drug'),
        ),
    ]
